language: go
go: [1.6]
sudo: false

install:
  # from http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4.4.5
  - make install

script:
  - make test-backend
  - make test-frontend
  - if [ "$TRAVIS_BRANCH" = "master" ]; then make release; fi;
  - if [ "$TRAVIS_BRANCH" != "master" ]; then make build; fi;