language: go
go: [1.6]
sudo: false
cache:
    directories:
        - gui/node_modules
        - vendor

install:
    # from http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4.4.5
    - make install

script:
    - go get github.com/mattn/goveralls
    - make coverage-backend
    - goveralls -coverprofile=build/pkgmirror.coverage -service=travis-ci
    - make test-frontend
    - make build

deploy:
    provider: releases
    api_key:
        secure: Qt4feiiX/1peF3107Z+HKHyXEri6oLdEENGLMAW7xyukKc6EhAwqsI5xKaJbAKfM7tyrvNyZaBil/2TW6bEmG7llnVvdoyzaUO3AZ6z/tpsQ8SJoI1ue5jvXvyK9LAzgVn2aKZHIgw6DcBF2mkkelAcNRIc92yGHyZnMOm0R5Fbc2iNakgwrHmHiTsrIgvGvURzWVtqV0LiWuMBeiqoek3j/BHtgl9ZzbBVWpvYsks6+BGS91x64ETiXaTPCIHHMvbP9r3Ps6ePqQbthqwLRsdLm9D0QS4bm0XD9faXYViue/a5mROxzzLgB9nwNTajvdAWN6mIGJw1aRI3GMZo4nzxk3CHHai+ybLHGVXPkDqE+o5dJMaoQ2TVoqLmRF6ddfyqhqs89aQ3g/6e5L5vtalm1eOEtK+s10e5+5x007syIz9R0ZE0UpdusuE8T9uhAdSmuALu/bW8K734eKhSRN1+sXdCinZaQ/BBWTn2rClnLfagR1xTwisdUJpZeZkcOZWZPx3D9zBU5L7TZGVTofm+3LeLXc24VoC7tY8GjhWP1smVvpzayyAu5//hSZFk+xHgv1ja1A5MeFcQQKi37FE7qTPpruWMK2UdVa6YbCGMYg5wANMK1Wj8/Df/KWM8x/qabAgeJcgA8dRKP8F1Ku2YGuTdVczyeuPaUv8+Csms=
    file:
        - build/darwin-amd64-pkgmirror
        - build/linux-amd64-pkgmirror
        - build/linux-386-pkgmirror
        - build/linux-arm-pkgmirror
        - build/linux-arm64-pkgmirror
    skip_cleanup: true
    overwrite: true
    on:
        tags: true
